# Generated by Django 5.1.2 on 2024-10-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0003_rename_name_name_district_nepali_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('nepali_name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth_ad', models.DateField()),
                ('date_of_birth_bs', models.DateField()),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('ethnic_group', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('nepali_father_name', models.CharField(max_length=255)),
                ('citizenship_no', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('issue_district', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='trainee/image/')),
                ('citizenship_front_image', models.FileField(upload_to='trainee/citizenship_image/front/')),
                ('citizenship_back_image', models.FileField(upload_to='trainee/citizenship_image/back/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_district', to='location.district')),
                ('palika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_palika', to='location.palika')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_province', to='location.province')),
            ],
        ),
    ]
