# Generated by Django 5.1.1 on 2024-10-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatory', '0002_remove_signatory_image_signatory_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatory',
            name='nepali_designation',
            field=models.CharField(default='devloper', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signatory',
            name='nepali_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signatory',
            name='nepali_name',
            field=models.CharField(default='amit', max_length=255),
            preserve_default=False,
        ),
    ]
