# Generated by Django 5.1.1 on 2024-10-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Palika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='location.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='location.province'),
        ),
    ]
