# Generated by Django 5.1.1 on 2024-10-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_district_name_name_palika_name_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='name_name',
            new_name='nepali_name',
        ),
        migrations.RenameField(
            model_name='palika',
            old_name='name_name',
            new_name='nepali_name',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='name_name',
            new_name='nepali_name',
        ),
    ]
