# Generated by Django 5.1.1 on 2024-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_rename_ocupation_contract_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='nepali_donation_by',
            field=models.CharField(default='amit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='nepali_location',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='nepali_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='nepali_occupation',
            field=models.CharField(default='devloper', max_length=255),
            preserve_default=False,
        ),
    ]
