# Generated by Django 5.1.1 on 2024-10-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0009_remove_batch_time_batch_end_date_batch_start_date'),
        ('contract', '0003_contract_nepali_donation_by_contract_nepali_location_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth_ad', models.DateField()),
                ('date_of_birth_bs', models.DateField()),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('ethnic_group', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('citizenship_no', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('issue_district', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='trainee/image/')),
                ('citizenship_front_image', models.FileField(upload_to='trainee/citizenship_image/front/')),
                ('citizenship_back_image', models.FileField(upload_to='trainee/citizenship_image/back/')),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_batch', to='batch.batch')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_contract', to='contract.contract')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_district', to='location.district')),
                ('palika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_palika', to='location.palika')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_province', to='location.province')),
            ],
        ),
    ]
