# Generated by Django 5.1.1 on 2024-10-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='nepali_father_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainee',
            name='nepali_name',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
