# Generated by Django 5.1.1 on 2024-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
