# Generated by Django 5.1.1 on 2024-10-01 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_alter_batch_contract'),
        ('contract', '0002_rename_ocupation_contract_occupation'),
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_batch', to='batch.batch'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_contract', to='contract.contract'),
        ),
    ]
