# Generated by Django 5.1.1 on 2024-10-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_alter_trainee_batch_alter_trainee_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='age',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
