# Generated by Django 5.1.1 on 2024-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_trainee_nepali_father_name_trainee_nepali_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
