# Generated by Django 5.1.1 on 2024-10-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_trainee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='citizenship_back_image',
            field=models.FileField(upload_to='trainee/citizenship_image/back/'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='citizenship_front_image',
            field=models.FileField(upload_to='trainee/citizenship_image/front/'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.FileField(upload_to='trainee/image/'),
        ),
    ]
