# Generated by Django 5.1.1 on 2024-10-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_trainee_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee/qr_codes/'),
        ),
    ]
