# Generated by Django 5.1.1 on 2024-10-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_alter_trainee_id'),
        ('trainee', '0004_alter_trainee_citizenship_back_image_and_more'),
    ]

    operations = [
    ]
