# Generated by Django 5.1.1 on 2024-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0005_merge_20241002_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='ward_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
