# Generated by Django 5.1.1 on 2024-10-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='nepali_name',
            field=models.CharField(default='amit', max_length=255),
            preserve_default=False,
        ),
    ]
