# Generated by Django 5.1.1 on 2024-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('tot', models.BooleanField(default=False)),
            ],
        ),
    ]
