# Generated by Django 5.1.1 on 2024-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='nepali_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
