# Generated by Django 5.1.1 on 2024-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract', models.TextField()),
                ('duration', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('seats', models.IntegerField()),
                ('trainer', models.ManyToManyField(related_name='batch_trainer', to='trainer.trainer')),
            ],
        ),
    ]
