# Generated by Django 5.1.1 on 2024-09-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_contract', to='trainer.trainer'),
        ),
    ]
