# Generated by Django 5.1.1 on 2024-09-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_alter_batch_contract'),
        ('contract', '0002_rename_ocupation_contract_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='contract',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='batch_contract', to='contract.contract'),
            preserve_default=False,
        ),
    ]
