# Generated by Django 5.1.1 on 2024-10-16 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_alter_batch_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='time',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
