# Generated by Django 5.1.1 on 2024-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, upload_to='backgrounds/')),
                ('qr_code_image', models.ImageField(blank=True, editable=False, upload_to='qr_codes/')),
            ],
        ),
    ]
