# Generated by Django 5.1.1 on 2024-09-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='project_image/')),
                ('description', models.CharField(max_length=255)),
                ('partner', models.CharField(max_length=255)),
                ('project_location', models.CharField(max_length=255)),
                ('project_duration', models.IntegerField()),
                ('result_and_activaties', models.CharField(max_length=255)),
                ('status', models.TextField(choices=[('Ongoing', 'Ongoing'), ('complete', 'complete')], max_length=50)),
            ],
        ),
    ]
