# Generated by Django 5.1.1 on 2024-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('Ongoing', 'Ongoing'), ('Complete', 'Complete')], max_length=50),
        ),
    ]
