# Generated by Django 5.1.1 on 2024-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_remove_publication_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pdf',
            field=models.FileField(default='', upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
