# Generated by Django 5.1.1 on 2024-09-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_alter_publication_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='long_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='short_description',
            field=models.TextField(max_length=500),
        ),
    ]
