# Generated by Django 5.1.1 on 2024-09-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_created_at_video_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
