name: Deploy Django via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 

    - name: Upload to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: 167.235.9.123
        username: etc@etcnepal.com.np
        password: Ultimate@22
        exclude: |
          templates/certificate/
        passive: true